version: '3.4'

services:
  app:
    image: node:10.16.0
    container_name: application
    env_file: ${PWD}/.env
    volumes:
      - ${PWD}/app:/home/node/app
      - ${PWD}/node_modules:/home/node/app/node_modules
      - ${PWD}/credentials:/home/node/.aws/credentials
    working_dir: /home/node/app
    command: node server.js
    networks:
      - microservices
    user: node

  worker-1:
    image: node:10.16.0
    container_name: worker-1
    env_file: ${PWD}/.env
    volumes:
      - ${PWD}/workers:/home/node/app
      - ${PWD}/node_modules:/home/node/app/node_modules
      - ${PWD}/credentials:/home/node/.aws/credentials
    working_dir: /home/node/app
    command: node server.js
    networks:
      - microservices
    user: node

networks:
  microservices:
    driver: bridge
